name: Changelog

on:
  push:
    branches:
      - master

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run changelog

      - name: Commit files
        env:
          CI_USER: ${{ secrets.USER }}
          CI_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add CHANGELOG.md && git commit -m 'chore: update changelog' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"
      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.USER }}
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master